version: '3'

services:
  api:
    build: ./api
    volumes:
      - ./api:/usr/src/app
    ports:
      - 6262:7000

  website-service:
    build: ./website
    volumes:
      - ./website:/usr/src/app
    ports:
      - 6969:3000
    depends_on:
      - api